# Generated by Django 4.2 on 2025-05-09 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_input', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Input',
                'verbose_name_plural': 'Clients Inputs',
            },
        ),
        migrations.CreateModel(
            name='AIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(default='With out response')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_final', models.BooleanField(default=True)),
                ('client_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.clientinput')),
            ],
            options={
                'verbose_name': 'AI Response',
                'verbose_name_plural': 'AI Responses',
            },
        ),
    ]
