# Generated by Django 4.2 on 2025-03-04 14:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_clientinput_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_final', models.BooleanField(default=True)),
                ('client_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.clientinput')),
            ],
            options={
                'verbose_name': 'AI Response',
                'verbose_name_plural': 'AI Responses',
            },
        ),
    ]
