# Generated by Django 4.2 on 2025-03-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_airesponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesponse',
            name='response_text',
            field=models.TextField(default='With out response'),
        ),
    ]
