# Generated by Django 4.2 on 2025-10-13 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auditors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('surname', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200)),
                ('company_email', models.CharField(blank=True, max_length=200, null=True)),
                ('document', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('cuit', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('company_logo', models.ImageField(blank=True, default='auditors/profile_images/default.png', null=True, upload_to='clients/profile_images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auditors.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=10)),
                ('body', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('auditor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditors.auditorprofile')),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientprofile')),
            ],
            options={
                'unique_together': {('client_profile', 'auditor_profile')},
            },
        ),
    ]
