# Generated by Django 4.2 on 2025-06-17 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_clientprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='auditors/profile_images/default.png', null=True, upload_to='clients/profile_images'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
