# Generated by Django 4.2 on 2025-06-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientprofile_profile_image_alter_clientprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='document',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
