# Generated by Django 4.2 on 2025-06-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientprofile_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='profile_image',
            new_name='company_logo',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='cuit',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
