# Generated by Django 4.2 on 2025-06-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_rename_profile_image_clientprofile_company_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='email',
        ),
    ]
