# Generated by Django 4.2 on 2025-07-01 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
