# Generated by Django 4.2 on 2025-08-06 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditors', '0013_alter_country_options_remove_country_code'),
        ('clients', '0009_alter_clientprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auditors.country'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='surname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
