# Generated by Django 4.2 on 2025-08-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_clientprofile_country_clientprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='company_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
