# Generated by Django 4.2 on 2025-08-11 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditors', '0014_alter_auditorprofile_country_and_more'),
        ('clients', '0011_clientprofile_company_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=10)),
                ('body', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('auditor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditors.auditorprofile')),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientprofile')),
            ],
            options={
                'unique_together': {('client_profile', 'auditor_profile')},
            },
        ),
    ]
