# Generated by Django 4.2 on 2025-10-13 20:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('document', models.CharField(max_length=60, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, default='auditors/profile_images/default.png', null=True, upload_to='auditors/profile_images')),
                ('location', models.CharField(max_length=80)),
                ('competency', models.CharField(blank=True, choices=[('internal', 'Internal Auditor'), ('lead', 'Lead Auditor'), ('external', 'External Auditor')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='IsoStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('certificate_file', models.FileField(upload_to='auditors/credentials/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auditor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditors.auditorprofile')),
            ],
        ),
        migrations.AddField(
            model_name='auditorprofile',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auditors.country'),
        ),
        migrations.AddField(
            model_name='auditorprofile',
            name='iso_standards',
            field=models.ManyToManyField(blank=True, to='auditors.isostandard'),
        ),
    ]
