# Generated by Django 4.2 on 2025-05-09 19:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('document', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_image', models.ImageField(blank=True, default='auditors/profile_images/default.png', null=True, upload_to='auditors/profile_images')),
                ('competency', models.CharField(blank=True, choices=[('internal', 'Internal Auditor'), ('lead', 'Lead Auditor'), ('external', 'External Auditor')], max_length=50, null=True)),
                ('iso_standard', models.CharField(blank=True, choices=[('9001', 'ISO 9001 (Quality Management)'), ('14001', 'ISO 14001 (Environmental Management)'), ('45001', 'ISO 45001 (Occupational Health & Safety)'), ('27001', 'ISO 27001 (Information Security)'), ('50001', 'ISO 50001 (Energy Management)'), ('22301', 'ISO 22301 (Business Continuity)'), ('37001', 'ISO 37001 (Anti-Bribery Management)')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('certificate_file', models.FileField(upload_to='auditors/credentials/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auditor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditors.auditorprofile')),
            ],
        ),
    ]
