# Generated by Django 4.2 on 2025-05-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorprofile',
            name='username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
