# Generated by Django 4.2 on 2025-11-08 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('auditors', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=200)),
                ('ia_analysis_result', models.TextField(blank=True, null=True)),
                ('ia_recommendations', models.TextField(blank=True, null=True)),
                ('ia_processed_at', models.DateTimeField(blank=True, null=True)),
                ('auditor_findings', models.TextField(blank=True, null=True)),
                ('auditor_recommendations', models.TextField(blank=True, null=True)),
                ('final_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ia_processing', 'AI Processing'), ('ia_completed', 'AI Analysis Completed'), ('assigned', 'Assigned to Auditor'), ('in_progress', 'Audit in Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ia_processing', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auditors.auditorprofile')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.clientprofile')),
            ],
        ),
    ]
