# Generated by Django 4.2 on 2025-05-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
