# Generated by Django 4.2 on 2025-05-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditors', '0002_auditorprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorprofile',
            name='competency',
            field=models.CharField(blank=True, choices=[('internal', 'Internal Auditor'), ('lead', 'Lead Auditor'), ('external', 'External Auditor')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditorprofile',
            name='document',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='auditorprofile',
            name='iso_standard',
            field=models.CharField(blank=True, choices=[('9001', 'ISO 9001 (Quality Management)'), ('14001', 'ISO 14001 (Environmental Management)'), ('45001', 'ISO 45001 (Occupational Health & Safety)'), ('27001', 'ISO 27001 (Information Security)'), ('50001', 'ISO 50001 (Energy Management)'), ('22301', 'ISO 22301 (Business Continuity)'), ('37001', 'ISO 37001 (Anti-Bribery Management)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditorprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditorprofile',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
