# Generated by Django 4.2 on 2025-05-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditors', '0003_auditorprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
