# Generated by Django 4.2 on 2025-05-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditors', '0004_auditorprofile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsoStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='auditorprofile',
            name='iso_standard',
        ),
        migrations.RemoveField(
            model_name='auditorprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='auditorprofile',
            name='iso_standards',
            field=models.ManyToManyField(blank=True, to='auditors.isostandard'),
        ),
    ]
