# Generated by Django 4.2 on 2025-06-02 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditors', '0005_isostandard_remove_auditorprofile_iso_standard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='certificate_file',
            field=models.FileField(upload_to='auditors/credentials/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg'])]),
        ),
    ]
