# Generated by Django 4.2 on 2025-06-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditors', '0006_alter_credential_certificate_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditorprofile',
            name='email',
        ),
    ]
