# Generated by Django 4.2 on 2025-08-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditors', '0007_remove_auditorprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorprofile',
            name='location',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
