# Generated by Django 4.2 on 2025-08-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditors', '0008_auditorprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorprofile',
            name='country',
            field=models.CharField(blank=True, null=True),
        ),
    ]
