# Generated by Django 4.2 on 2025-08-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditors', '0010_country_alter_auditorprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorprofile',
            name='country',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
