# Generated by Django 4.2 on 2025-08-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditors', '0011_alter_auditorprofile_country_delete_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='auditorprofile',
            name='country',
            field=models.ForeignKey(blank=True, max_length=80, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auditors.country'),
        ),
    ]
