# Generated by Django 4.2 on 2025-08-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditors', '0012_country_alter_auditorprofile_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
    ]
