# Generated by Django 4.2 on 2025-08-08 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditors', '0013_alter_country_options_remove_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorprofile',
            name='country',
            field=models.ForeignKey(max_length=80, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auditors.country'),
        ),
        migrations.AlterField(
            model_name='auditorprofile',
            name='document',
            field=models.CharField(default='', max_length=60, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditorprofile',
            name='location',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditorprofile',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditorprofile',
            name='phone',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditorprofile',
            name='surname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
