# Generated by Django 4.2 on 2025-04-15 12:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('document', models.PositiveIntegerField()),
                ('photo', models.ImageField(default='auditors/photos/default.png', upload_to='auditors/photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Profile Photo')),
                ('location', models.CharField(max_length=200)),
                ('competency', models.CharField(choices=[('internal', 'Internal Auditor'), ('lead', 'Lead Auditor'), ('external', 'External Auditor')], default='internal', max_length=50)),
                ('iso_standard', models.CharField(choices=[('9001', 'ISO 9001 (Quality Management)'), ('14001', 'ISO 14001 (Environmental Management)'), ('45001', 'ISO 45001 (Occupational Health & Safety)'), ('27001', 'ISO 27001 (Information Security)'), ('50001', 'ISO 50001 (Energy Management)'), ('22301', 'ISO 22301 (Business Continuity)'), ('37001', 'ISO 37001 (Anti-Bribery Management)')], default='9001', max_length=20)),
                ('email1', models.EmailField(max_length=254, null=True)),
                ('email2', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('documents', models.FileField(blank=True, null=True, upload_to='auditor_docs/', verbose_name='Douments PDF')),
                ('submission_date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('document', models.PositiveIntegerField()),
                ('photo', models.ImageField(default='auditors/photos/default.png', upload_to='auditors/photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Profile Photo')),
                ('location', models.CharField(max_length=200)),
                ('competency', models.CharField(choices=[('internal', 'Internal Auditor'), ('lead', 'Lead Auditor'), ('external', 'External Auditor')], default='internal', max_length=50)),
                ('iso_standard', models.CharField(choices=[('9001', 'ISO 9001 (Quality Management)'), ('14001', 'ISO 14001 (Environmental Management)'), ('45001', 'ISO 45001 (Occupational Health & Safety)'), ('27001', 'ISO 27001 (Information Security)'), ('50001', 'ISO 50001 (Energy Management)'), ('22301', 'ISO 22301 (Business Continuity)'), ('37001', 'ISO 37001 (Anti-Bribery Management)')], default='9001', max_length=20)),
                ('email1', models.EmailField(max_length=254, null=True)),
                ('email2', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('documents', models.FileField(blank=True, null=True, upload_to='auditor_docs/', verbose_name='Douments PDF')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
