# Generated by Django 4.2 on 2025-04-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorapplication',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
