# Generated by Django 4.2 on 2025-04-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditorapplication',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='auditorapplication',
            name='experience',
        ),
        migrations.AddField(
            model_name='auditorapplication',
            name='document',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditorapplication',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='auditorapplication',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
