# Generated by Django 4.2 on 2025-05-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditorApplication',
        ),
    ]
