# Generated by Django 4.2 on 2025-04-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_auditorapplication_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorapplication',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='auditor_docs/', verbose_name='Douments PDF'),
        ),
        migrations.AlterField(
            model_name='auditorapplication',
            name='document',
            field=models.PositiveIntegerField(),
        ),
    ]
