# Generated by Django 4.2 on 2025-04-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auditorapplication_registration_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorapplication',
            name='document',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='auditorprofile',
            name='document',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
