# Generated by Django 4.2 on 2025-04-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auditorapplication_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorapplication',
            name='competency',
            field=models.CharField(choices=[('internal', 'Internal Auditor'), ('lead', 'Lead Auditor'), ('external', 'External Auditor')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditorapplication',
            name='iso_standard',
            field=models.CharField(choices=[('9001', 'ISO 9001 (Quality Management)'), ('14001', 'ISO 14001 (Environmental Management)'), ('45001', 'ISO 45001 (Occupational Health & Safety)'), ('27001', 'ISO 27001 (Information Security)'), ('50001', 'ISO 50001 (Energy Management)'), ('22301', 'ISO 22301 (Business Continuity)'), ('13485', 'ISO 13485 (Medical Devices)'), ('22000', 'ISO 22000 (Food Safety)'), ('17025', 'ISO/IEC 17025 (Testing Laboratories)'), ('37001', 'ISO 37001 (Anti-Bribery Management)')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
