# Generated by Django 4.2 on 2025-04-07 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auditorapplication_competency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorapplication',
            name='photo',
            field=models.ImageField(default='auditors/photos/default.webp', upload_to='auditors/photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Profile Photo'),
        ),
    ]
