# Generated by Django 4.2 on 2025-04-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auditorapplication_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorapplication',
            name='iso_standard',
            field=models.CharField(choices=[('9001', 'ISO 9001 (Quality Management)'), ('14001', 'ISO 14001 (Environmental Management)'), ('45001', 'ISO 45001 (Occupational Health & Safety)'), ('27001', 'ISO 27001 (Information Security)'), ('50001', 'ISO 50001 (Energy Management)'), ('22301', 'ISO 22301 (Business Continuity)'), ('37001', 'ISO 37001 (Anti-Bribery Management)')], max_length=20),
        ),
    ]
