# Generated by Django 4.2 on 2025-04-08 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_auditorapplication_iso_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorapplication',
            name='photo',
            field=models.ImageField(blank=True, default='auditors/photos/default.png', upload_to='auditors/photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Profile Photo'),
        ),
    ]
