# Generated by Django 4.2 on 2025-04-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_auditorapplication_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditorapplication',
            name='email',
        ),
        migrations.AddField(
            model_name='auditorapplication',
            name='email1',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditorapplication',
            name='email2',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
